// ─── pushRoutes.js ────────────────────────────────────────────────────────────
// Handles all push notification registration, unsubscription, and broadcasting
// for both web (VAPID / browser push) and native Android APK (Firebase FCM).
//
// Mount this in your main server file:
//   const pushRoutes = require('./pushRoutes');
//   app.use('/api/push', authMiddleware, pushRoutes);
//
// Environment variables required (.env):
//   VAPID_PUBLIC_KEY   – generated by web-push, starts with "BN..."
//   VAPID_PRIVATE_KEY  – generated by web-push
//   VAPID_EMAIL        – mailto: address, e.g. "mailto:you@yourdomain.com"
//   FIREBASE_SERVICE_ACCOUNT_PATH – path to your google-services JSON key file
//                                   OR set FIREBASE_SERVICE_ACCOUNT_JSON with the
//                                   full JSON string (better for env-var deployments)
//
// Generate VAPID keys once:
//   node -e "const wp=require('web-push'); const k=wp.generateVAPIDKeys(); console.log(k);"

const express   = require('express');
const webpush   = require('web-push');
const admin     = require('firebase-admin');
const User      = require('./User'); // adjust path if needed

const router = express.Router();

// ─── Initialise web-push (VAPID) ─────────────────────────────────────────────
if (!process.env.VAPID_PUBLIC_KEY || !process.env.VAPID_PRIVATE_KEY) {
  console.warn('⚠️  VAPID keys not set — web push will not work. Set VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY, VAPID_EMAIL in .env');
} else {
  webpush.setVapidDetails(
    process.env.VAPID_EMAIL || 'mailto:admin@milledgevilleconnect.com',
    process.env.VAPID_PUBLIC_KEY,
    process.env.VAPID_PRIVATE_KEY
  );
}

// ─── Initialise Firebase Admin (FCM) ─────────────────────────────────────────
if (!admin.apps.length) {
  try {
    let serviceAccount;
    if (process.env.FIREBASE_SERVICE_ACCOUNT_JSON) {
      // Preferred for cloud deployments: store the whole JSON as an env var
      serviceAccount = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON);
    } else if (process.env.FIREBASE_SERVICE_ACCOUNT_PATH) {
      serviceAccount = require(process.env.FIREBASE_SERVICE_ACCOUNT_PATH);
    } else {
      console.warn('⚠️  Firebase service account not configured — FCM (Android APK) push will not work.');
    }
    if (serviceAccount) {
      admin.initializeApp({
        credential: admin.credential.cert(serviceAccount)
      });
      console.log('✅ Firebase Admin SDK initialised');
    }
  } catch (err) {
    console.error('❌ Firebase Admin init failed:', err.message);
  }
}

// ─── GET /api/push/vapid-public-key ──────────────────────────────────────────
// Returns the VAPID public key so the browser client can subscribe.
// This route does NOT require auth — the browser needs it before login too.
router.get('/vapid-public-key', (req, res) => {
  if (!process.env.VAPID_PUBLIC_KEY) {
    return res.status(503).json({ error: 'VAPID not configured' });
  }
  res.json({ key: process.env.VAPID_PUBLIC_KEY });
});

// ─── POST /api/push/subscribe  (web / browser VAPID) ─────────────────────────
// Body: { subscription: { endpoint, expirationTime, keys: { p256dh, auth } } }
router.post('/subscribe', async (req, res) => {
  const userId = req.user?._id || req.user?.id;
  if (!userId) return res.status(401).json({ message: 'Not authenticated' });

  const { subscription } = req.body;
  if (!subscription?.endpoint || !subscription?.keys?.p256dh || !subscription?.keys?.auth) {
    return res.status(400).json({ message: 'Invalid subscription object' });
  }

  try {
    const user = await User.findById(userId);
    if (!user) return res.status(404).json({ message: 'User not found' });

    user.addWebSub(subscription);
    await user.save();

    console.log(`✅ Web push subscription saved for user ${userId} (endpoint: ${subscription.endpoint.slice(0, 60)}...)`);
    res.json({ message: 'Subscribed' });
  } catch (err) {
    console.error('❌ /push/subscribe error:', err);
    res.status(500).json({ message: 'Failed to save subscription' });
  }
});

// ─── POST /api/push/native-subscribe  (Android APK / FCM) ────────────────────
// Body: { token: "FCM_TOKEN_STRING", platform: "android" | "ios" }
router.post('/native-subscribe', async (req, res) => {
  const userId = req.user?._id || req.user?.id;
  if (!userId) return res.status(401).json({ message: 'Not authenticated' });

  const { token, platform } = req.body;
  if (!token || typeof token !== 'string' || token.length < 10) {
    return res.status(400).json({ message: 'Invalid FCM token' });
  }

  try {
    const user = await User.findById(userId);
    if (!user) return res.status(404).json({ message: 'User not found' });

    user.addFcmToken(token);
    await user.save();

    console.log(`✅ FCM token saved for user ${userId} platform=${platform || 'android'} token=${token.slice(0, 20)}...`);
    res.json({ message: 'Native subscription saved', pushEnabled: user.pushEnabled });
  } catch (err) {
    console.error('❌ /push/native-subscribe error:', err);
    res.status(500).json({ message: 'Failed to save FCM token' });
  }
});

// ─── POST /api/push/unsubscribe ───────────────────────────────────────────────
// Removes ALL push subscriptions (both web and FCM) for the current user.
// Called when the user turns off push notifications in their profile.
router.post('/unsubscribe', async (req, res) => {
  const userId = req.user?._id || req.user?.id;
  if (!userId) return res.status(401).json({ message: 'Not authenticated' });

  // Optional: body may contain { endpoint } for web or { token } for FCM
  // to remove a specific subscription rather than all.
  const { endpoint, token } = req.body || {};

  try {
    const user = await User.findById(userId);
    if (!user) return res.status(404).json({ message: 'User not found' });

    if (endpoint) {
      user.removeWebSub(endpoint);
    } else if (token) {
      user.removeFcmToken(token);
    } else {
      // Wipe everything
      user.webPushSubscriptions = [];
      user.fcmTokens            = [];
      user.pushEnabled          = false;
    }

    await user.save();
    res.json({ message: 'Unsubscribed' });
  } catch (err) {
    console.error('❌ /push/unsubscribe error:', err);
    res.status(500).json({ message: 'Failed to unsubscribe' });
  }
});

// ─── BROADCAST HELPERS ────────────────────────────────────────────────────────

/**
 * Send a push notification to a single user.
 * Handles both web push (VAPID) and FCM (native Android).
 * Automatically cleans up expired/invalid subscriptions.
 *
 * @param {Object} user         - Mongoose User document
 * @param {Object} payload      - { title, body, url, icon, badge, data }
 */
async function pushToUser(user, payload) {
  if (!user.pushEnabled) return;

  const payloadStr = JSON.stringify({
    title: payload.title || 'Milledgeville Connect',
    body:  payload.body  || '',
    url:   payload.url   || '/',
    icon:  payload.icon  || '/icons/icon-192.png',
    badge: payload.badge || '/icons/badge-72.png',
    data:  payload.data  || {}
  });

  const webResults  = [];
  const fcmResults  = [];

  // ── Web push (VAPID) ─────────────────────────────────────────────────────
  for (const sub of user.webPushSubscriptions || []) {
    try {
      await webpush.sendNotification(sub, payloadStr);
    } catch (err) {
      if (err.statusCode === 410 || err.statusCode === 404) {
        // Subscription expired — remove it
        console.log(`🗑️  Removing expired web sub for user ${user._id}`);
        webResults.push({ remove: sub.endpoint });
      } else {
        console.error(`❌ Web push failed for user ${user._id}:`, err.message);
      }
    }
  }

  // ── FCM (native Android/iOS) ─────────────────────────────────────────────
  if (admin.apps.length > 0) {
    for (const fcmToken of user.fcmTokens || []) {
      try {
        await admin.messaging().send({
          token: fcmToken,
          notification: {
            title: payload.title || 'Milledgeville Connect',
            body:  payload.body  || ''
          },
          data: {
            url:  payload.url  || '/',
            ...(payload.data || {})
          },
          android: {
            notification: {
              icon:        'notification_icon',   // must match your drawable resource name
              color:       '#059669',
              clickAction: 'FLUTTER_NOTIFICATION_CLICK'
            },
            priority: 'high'
          }
        });
      } catch (err) {
        const code = err.errorInfo?.code || '';
        if (
          code === 'messaging/registration-token-not-registered' ||
          code === 'messaging/invalid-registration-token'
        ) {
          console.log(`🗑️  Removing invalid FCM token for user ${user._id}`);
          fcmResults.push({ remove: fcmToken });
        } else {
          console.error(`❌ FCM failed for user ${user._id}:`, err.message);
        }
      }
    }
  }

  // Cleanup stale subs/tokens without blocking the caller
  if (webResults.length > 0 || fcmResults.length > 0) {
    setImmediate(async () => {
      try {
        const fresh = await User.findById(user._id);
        if (!fresh) return;
        for (const r of webResults)  fresh.removeWebSub(r.remove);
        for (const r of fcmResults)  fresh.removeFcmToken(r.remove);
        await fresh.save();
      } catch (e) { /* non-critical */ }
    });
  }
}

/**
 * Broadcast a push notification to all users who have a given preference enabled.
 *
 * @param {string} notifyField  - The User schema boolean field name,
 *                                e.g. 'notifyDeals', 'notifyEvents', 'notifyShoutouts',
 *                                     'notifyLostFound', 'notifyMarketplace', 'notifyMessages'
 * @param {Object} payload      - { title, body, url, icon, data }
 * @param {string[]} [exclude]  - Array of user _id strings to skip (e.g. the post author)
 */
async function broadcastPush(notifyField, payload, exclude = []) {
  if (!process.env.VAPID_PUBLIC_KEY && admin.apps.length === 0) {
    console.warn('broadcastPush: no push provider configured, skipping');
    return;
  }

  const query = {
    pushEnabled: true,
    [notifyField]: true
  };
  if (exclude.length > 0) {
    query._id = { $nin: exclude };
  }

  try {
    const users = await User.find(query).lean(false); // need methods
    console.log(`📢 Broadcasting "${payload.title}" to ${users.length} users (field: ${notifyField})`);
    await Promise.allSettled(users.map(u => pushToUser(u, payload)));
  } catch (err) {
    console.error('❌ broadcastPush error:', err);
  }
}

/**
 * Send a push notification to a single specific user by their _id.
 * Used for direct message notifications.
 *
 * @param {string} userId   - Recipient user _id
 * @param {Object} payload  - { title, body, url, data }
 */
async function pushToUserId(userId, payload) {
  try {
    const user = await User.findById(userId);
    if (!user) return;
    if (!user.pushEnabled || !user.notifyMessages) return;
    await pushToUser(user, payload);
  } catch (err) {
    console.error('❌ pushToUserId error:', err);
  }
}

// Export helpers for use in your other route files
module.exports = router;
module.exports.broadcastPush = broadcastPush;
module.exports.pushToUserId  = pushToUserId;
module.exports.pushToUser    = pushToUser;